### ISSUE TITLE
Branding Reboot Checklist

### ISSUE THREAD

**Issue by reynoldsalec** [thinktandem/thinktandem.io#2]
**Performance/SEO/Cleaning House**

- [x] Implement styles from style guide 
- [x] Get rid of rest of Penthouse stuff
- [ ] CDN/other caching for performance?

**Home Page**

- [ ] New Navbar
- [x] Value Proposition and Call to Action
- [x] Service Descriptions (Development/Strategy/Rescue)
- [x] Client Logos
- [x] New Quotes
- [x] Footer Menu (link technologies/industries, link to Services)

**About Us**

- [x] Add Joel
- [ ] Get rid of long bios, make a one-line structure
- [x] Emphasis on what Tandem collectively has done: stats, languages known, summary
- [ ] Francisco standardize language icons
- [ ] Get new bio info for everyone

**Contact Page**

- [ ] Adding locations?

**Blog**

- [ ] Update blog branding

**Services**

- [ ] Development/Strategy/Rescue --> Layout the pages

**Work**

- [ ]

**Comment by pirog** [comment]
@reynoldsalec did some research and i think we also need to figure out how to emphasize our accomplishments better eg:

* You and I co-founded another company
* Geoff is a core backdrop contributor
* All the open source projects we've invented or contributed to
* Relevant materials from events we've helped at (eg video at MIT of Kalatheme, SANDcamp trainings)
